services:
  postgres:
    image: postgres:18.1-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cliplink
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cliplink"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  nats-data: